### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 238g** [238g/Parace#7]
- [ ] ~~縦横スマホ対応。縦なら3×6、横なら6×3。~~
- [x] タイトル画面のスタートはボタン。
- [x] フルスクリーンボタン搭載。
- [x] ミュートボタン搭載。
- [x] ミュートボタン搭載。->TEST
- [x] スタート後に説明文、
- [x] 木は毎度生成なので全てデリートが必要
- [x] 入れ替えの時に炎アニメーション。
- [x] タイム30秒、60秒、90秒、説明後のボタンで決める？
- [x] →余裕があれば、みとちゃんとかえでちゃんとりんちゃんのイラスト入れる→306090秒わけ？
- [x] お手付きはマイナス2秒？
- [x] スコアは前のクリックとの時間差二乗三乗で比率大きく。
- [x] 321スタートのカウントダウンついーん、効果音。
- [ ] タイムアップ効果音。
- [x] スコア表示、ツイート表示。
- [x] だうんぽいんたー、duration,delay,tweenkey,oncomplete
